//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenSys.MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_menu
    {
        public long id { get; set; }
        public string code { get; set; }
        public string pcode { get; set; }
        public string pcodes { get; set; }
        public string name { get; set; }
        public string icon { get; set; }
        public string url { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> levels { get; set; }
        public Nullable<int> ismenu { get; set; }
        public string tips { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> isopen { get; set; }
    }
}
