//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public string alias { get; set; }
        public string site { get; set; }
        public string dev_type { get; set; }
        public string dev_model { get; set; }
        public string account { get; set; }
        public string password { get; set; }
        public string uuid { get; set; }
        public string rtsp_url { get; set; }
        public string ip { get; set; }
        public Nullable<int> media_port { get; set; }
    }
}
