//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ipcam
    {
        public Nullable<double> algo_h { get; set; }
        public Nullable<double> algo_w { get; set; }
        public string alias_name { get; set; }
        public Nullable<double> ebd_ebikeThre { get; set; }
        public Nullable<double> ebd_enable { get; set; }
        public Nullable<double> ebd_fps { get; set; }
        public string ebd_fri { get; set; }
        public string ebd_mon { get; set; }
        public Nullable<double> ebd_personThre { get; set; }
        public string ebd_sat { get; set; }
        public string ebd_sun { get; set; }
        public Nullable<double> ebd_trigmodel { get; set; }
        public string ebd_tue { get; set; }
        public string ebd_tur { get; set; }
        public string ebd_wed { get; set; }
        public Nullable<double> fsd_enable { get; set; }
        public Nullable<double> fsd_fps { get; set; }
        public string fsd_fri { get; set; }
        public string fsd_mon { get; set; }
        public string fsd_sat { get; set; }
        public string fsd_sun { get; set; }
        public string fsd_tue { get; set; }
        public string fsd_tur { get; set; }
        public string fsd_wed { get; set; }
        public Nullable<double> manual { get; set; }
        public Nullable<double> opa4t_enable { get; set; }
        public Nullable<double> opa4t_fps { get; set; }
        public string opa4t_fri { get; set; }
        public string opa4t_mon { get; set; }
        public Nullable<double> opa4t_roi0_enable { get; set; }
        public Nullable<double> opa4t_roi0_id { get; set; }
        public Nullable<double> opa4t_roi0_pt0_x { get; set; }
        public Nullable<double> opa4t_roi0_pt0_y { get; set; }
        public Nullable<double> opa4t_roi0_pt1_x { get; set; }
        public Nullable<double> opa4t_roi0_pt1_y { get; set; }
        public Nullable<double> opa4t_roi0_pt2_x { get; set; }
        public Nullable<double> opa4t_roi0_pt2_y { get; set; }
        public Nullable<double> opa4t_roi0_pt3_x { get; set; }
        public Nullable<double> opa4t_roi0_pt3_y { get; set; }
        public Nullable<double> opa4t_roi0_ptnum { get; set; }
        public Nullable<double> opa4t_roi0_sensitivity { get; set; }
        public Nullable<double> opa4t_roi_num { get; set; }
        public string opa4t_sat { get; set; }
        public string opa4t_sun { get; set; }
        public Nullable<double> opa4t_trigmodel { get; set; }
        public string opa4t_tue { get; set; }
        public string opa4t_tur { get; set; }
        public string opa4t_wed { get; set; }
        public Nullable<double> pfr_enable { get; set; }
        public Nullable<double> pfr_fps { get; set; }
        public string pfr_fri { get; set; }
        public string pfr_mon { get; set; }
        public string pfr_sat { get; set; }
        public string pfr_sun { get; set; }
        public string pfr_tue { get; set; }
        public string pfr_tur { get; set; }
        public string pfr_wed { get; set; }
        public Nullable<double> post_alarm { get; set; }
        public Nullable<double> pre_alarm { get; set; }
        public string rtsp_account { get; set; }
        public string rtsp_passwd { get; set; }
        public string rtspurl { get; set; }
        public Nullable<double> ssc_abnormalthr { get; set; }
        public Nullable<double> ssc_enable { get; set; }
        public Nullable<double> ssc_fps { get; set; }
        public string ssc_fri { get; set; }
        public string ssc_mon { get; set; }
        public Nullable<double> ssc_roi0_enable { get; set; }
        public Nullable<double> ssc_roi0_pt0_x { get; set; }
        public Nullable<double> ssc_roi0_pt0_y { get; set; }
        public Nullable<double> ssc_roi0_pt1_x { get; set; }
        public Nullable<double> ssc_roi0_pt1_y { get; set; }
        public Nullable<double> ssc_roi0_pt2_x { get; set; }
        public Nullable<double> ssc_roi0_pt2_y { get; set; }
        public Nullable<double> ssc_roi0_pt3_x { get; set; }
        public Nullable<double> ssc_roi0_pt3_y { get; set; }
        public Nullable<double> ssc_roi0_ptnum { get; set; }
        public Nullable<double> ssc_roi_num { get; set; }
        public string ssc_sat { get; set; }
        public string ssc_sun { get; set; }
        public string ssc_tue { get; set; }
        public string ssc_tur { get; set; }
        public string ssc_wed { get; set; }
        public string uuid { get; set; }
        public Nullable<double> wca_enable { get; set; }
        public Nullable<double> wca_fps { get; set; }
        public string wca_fri { get; set; }
        public string wca_mon { get; set; }
        public string wca_sat { get; set; }
        public string wca_sun { get; set; }
        public string wca_tue { get; set; }
        public string wca_tur { get; set; }
        public string wca_wed { get; set; }
        public Nullable<double> whitelist { get; set; }
        public Nullable<int> ebd_cpu { get; set; }
        public Nullable<int> fsd_cpu { get; set; }
        public Nullable<int> opa4t_cpu { get; set; }
        public Nullable<int> pfr_cpu { get; set; }
        public Nullable<int> ssc_cpu { get; set; }
        public Nullable<int> wca_cpu { get; set; }
    }
}
