//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_user
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string role_id { get; set; }
        public string name { get; set; }
        public string dept_id { get; set; }
        public string position { get; set; }
        public string qualification { get; set; }
        public string id_number { get; set; }
        public string phone_number { get; set; }
        public string photo { get; set; }
        public Nullable<System.DateTime> register_date { get; set; }
    }
}
