//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_basicconfig
    {
        public int id { get; set; }
        public string name { get; set; }
        public string logo { get; set; }
        public string ui_type { get; set; }
        public string app_support { get; set; }
        public string beep { get; set; }
        public string video_src { get; set; }
        public string prtsc_path { get; set; }
        public string video_path { get; set; }
    }
}
